services:
  app:
    # 서버에서는 build 대신 GHCR 이미지 사용
    # Docker 이미지 이름은 소문자만 허용
    image: ghcr.io/team8-toyproject4/tai_java_backend:latest
    container_name: spring-boot-app
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
