spring:
  application:
    name: tai_backend
  config:
    import: optional:file:.env[.properties] # .env import
  # database setting
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.optimizer.pooled.preferred: false
# 로깅 설정
logging:
  level:
    root: INFO
    com.team8.tai_backend: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

python-url: ${PYTHON_URL}
front-url: ${FRONT_URL}